<form id='import_form' enctype="multipart/form-data" method='post' action='/jqgrid/jqgrid/oper/import/db/<?php echo $this->db;?>/table/<?php echo $this->table;?>' target='hidden_frame'>
	<?php
		$ces1 = array(
			array('name'=>'testcase_type_id', 'label'=>'Testcase Type', 'DATA_TYPE'=>'int', 'editable'=>true, 'editrules'=>array('required'=>true), 'type'=>'select', 'editoptions'=>array('value'=>$this->testcase_type['value'])),
		);
		$ces1[] = array('name'=>'test_env_id', 'label'=>'Test Env', 'DATA_TYPE'=>'int', 'editable'=>true, 'editrules'=>array('required'=>true), 'type'=>'select', 'editoptions'=>array('value'=>$this->test_env['value']));
		$ces2 = array(
			array('name'=>'config_file', 'label'=>'Config Type', 'DATA_TYPE'=>'int', 'editable'=>true, 'editrules'=>array('required'=>true), 'type'=>'select', 'editoptions'=>array('value'=>$this->config_file)),
			array('name'=>'owner_id', 'label'=>'Owner', 'DATA_TYPE'=>'int', 'editable'=>true, 'editrules'=>array('required'=>true), 'type'=>'select', 'editoptions'=>array('value'=>$this->owner['value'])),
			array('name'=>'prj_ids', 'label'=>'Project', 'type'=>'select', 'editable'=>true, 'editrules'=>array('required'=>true), 'editoptions'=>array('value'=>$this->prj['value'])),
			array('name'=>'uploaded_file', 'label'=>'File', 'DATA_TYPE'=>'int', 'editable'=>true, 'editrules'=>array('required'=>true), 'type'=>'file')
		);
		$ces = array_merge($ces1, $ces2);
		if(!empty($this->defval)){
			foreach($ces as &$v){
				if(in_array($v['name'], array_keys($this->defval))){
					// if('owner_id' != $v['name'] && 'test_env_id' != $v['name'])
						// $v['editable'] = false;
					$v['defval'] = $this->defval[$v['name']];
				}
			}
		}
		$tool = toolFactory::get('kf');
		$tool->cf($ces, true, 'new', 1, false, array(), true);
	?>
</form>
<iframe name='hidden_frame' id='hidden_frame' width="100%"></iframe>

