Please select the Add Cases type:
<table>
	<tr>
		<td>
			<label for="add_from_query_list">
				<input type="radio" name="case_add_type" id="add_from_query_list" checked="checked" value="case_list"> 
				Add Cases From Case List To Current Cycle
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="add_from_cycle">
				<input type="radio" name="case_add_type" id="add_from_cycle" value="cycle_list"> 
				Add Cases From Other Cycle To Current Cycle
			</label> 
		</td> 
	</tr>
</table> 
