<table>
	<tr>
		<td>
			<label for="export_type_default">
				<input type="radio" name="export_type" id="export_type_default" checked="checked" value="excel"> 
				Export the selected rows
			</label> 
		</td> 
	</tr> 
	<tr>
		<td>
			<label for="export_type_report">
				<input type="radio" name="export_type" id="export_type_report" value="report"> 
				Report for the selected rows
				<div id='div_for_report_options'>
					<?php
						echo $this->partial('srs_node_report_options.phtml', $this);
					?>
				</div>
			</label> 
		</td> 
	</tr> 
</table> 
